# Generated by Django 4.2.1 on 2023-07-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('daysoftour', models.CharField(max_length=20)),
                ('typeoftour', models.CharField(max_length=50)),
                ('Otime', models.CharField(max_length=20)),
                ('ctime', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.company')),
            ],
            options={
                'verbose_name_plural': 'TravelAgencies',
                'db_table': 'travelagency',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('review', models.CharField(max_length=200)),
                ('applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.applicant')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('website', models.CharField(max_length=30)),
                ('Otime', models.TimeField(max_length=20)),
                ('ctime', models.TimeField(max_length=20)),
                ('about', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.company')),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('meals', models.CharField(max_length=20)),
                ('accommodation', models.CharField(max_length=20)),
                ('placeofa', models.CharField(max_length=50)),
                ('dates', models.DateField()),
                ('admission', models.CharField(max_length=20)),
                ('helpno', models.IntegerField()),
                ('canceldate', models.DateField()),
                ('additionalinfo', models.CharField(max_length=100)),
                ('startpoint', models.CharField(max_length=50)),
                ('place1', models.CharField(max_length=50)),
                ('place2', models.CharField(max_length=50)),
                ('place3', models.CharField(max_length=50)),
                ('Travelagency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.travelagency')),
            ],
            options={
                'verbose_name_plural': 'Package_TAs',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('package', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('aboutofhotel', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=60)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.company')),
            ],
            options={
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotel',
            },
        ),
    ]
