# Generated by Django 4.2.1 on 2023-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UKiyoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
