# Generated by Django 4.2.1 on 2023-07-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UKiyoapp', '0002_applicant_about_applicant_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
