# Generated by Django 4.2.1 on 2023-07-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UKiyoapp', '0003_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('meals', models.CharField(max_length=20)),
                ('accommodation', models.CharField(max_length=20)),
                ('placeofa', models.CharField(max_length=50)),
                ('dates', models.DateField()),
                ('admission', models.CharField(max_length=20)),
                ('helpno', models.IntegerField()),
                ('canceldate', models.DateField()),
                ('additionalinfo', models.CharField(max_length=100)),
                ('startpoint', models.CharField(max_length=50)),
                ('place1', models.CharField(max_length=50)),
                ('place2', models.CharField(max_length=50)),
                ('place3', models.CharField(max_length=50)),
                ('Travelagency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.travelagency')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.company')),
            ],
            options={
                'verbose_name_plural': 'Package_TAs',
                'db_table': 'packages',
            },
        ),
    ]
