# Generated by Django 4.2.1 on 2023-07-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UKiyoapp', '0005_packages_price_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.company')),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UKiyoapp.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'db_table': 'menu',
            },
        ),
    ]
