# Generated by Django 4.2.1 on 2023-08-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='travelAgency',
        ),
    ]
